# Generated by Django 4.0.5 on 2022-11-16 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminRegistration',
            new_name='admin_registration',
        ),
        migrations.RenameModel(
            old_name='userRegistration',
            new_name='user_registration',
        ),
    ]
