# Generated by Django 4.0.5 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_adminregistration_admin_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_registration',
            name='name_of_org',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
