# Generated by Django 4.0.5 on 2022-11-16 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_alter_admin_registration_name_of_org'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='password',
        ),
        migrations.AddField(
            model_name='user_registration',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
