# Generated by Django 4.0.5 on 2022-11-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_user_registration_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_registration',
            old_name='organisation_foundation_year',
            new_name='year_of_foundation',
        ),
    ]
